# Generated by Django 4.2.5 on 2023-09-18 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Info'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='category',
            name='cretaed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='logo',
            field=models.ImageField(blank=True, default='site/default_logo.png', upload_to='site/'),
        ),
    ]
