# Generated by Django 4.2.5 on 2023-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_options_alter_info_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, default='Dhaka,Bangladesh', max_length=200),
        ),
        migrations.AddField(
            model_name='info',
            name='facabook',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='info',
            name='instagram',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='info',
            name='linkedin',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='info',
            name='twitter',
            field=models.CharField(blank=True, default='#', max_length=100),
        ),
    ]
