# Generated by Django 4.2.5 on 2023-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_info_address_info_facabook_info_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='about_img',
            field=models.ImageField(blank=True, default='site/default_about.png', upload_to='site/'),
        ),
    ]
