# Generated by Django 4.2.5 on 2023-10-07 10:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_about_img_info_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='professionals/')),
                ('bio', ckeditor.fields.RichTextField()),
                ('objective', ckeditor.fields.RichTextField()),
                ('professional_experience', ckeditor.fields.RichTextField()),
                ('education', ckeditor.fields.RichTextField()),
                ('skills', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='img',
        ),
    ]
