# Generated by Django 4.2.5 on 2023-10-07 10:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_professional_remove_info_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='story',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
