# Generated by Django 4.2.5 on 2023-10-07 10:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_professional_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='contact',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
